version: 0.2

env:
  variables:
    SOLUTION: .\msmq-to-sqs.sln
    PACKAGE_DIRECTORY: .\packages
    DOTNET_FRAMEWORK: 4.7

phases:
  build:
    commands:
      - '& nuget restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& msbuild -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'
artifacts:
  files:
    - .\msmq-to-sqs.sln\bin\Debug\*